insert into author (id, create_date, edit_date, first_name, last_name, bio) values (1, current_timestamp, current_timestamp,'Gleda', 'Rickaert', 'Networked asymmetric middleware');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (2, current_timestamp, current_timestamp,'Antonietta', 'Clarkin', 'Total full-range hierarchy');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (3, current_timestamp, current_timestamp,'Traver', 'Nornasell', 'Phased mission-critical encoding');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (4, current_timestamp, current_timestamp,'Weston', 'Eastbury', 'User-friendly cohesive open architecture');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (5, current_timestamp, current_timestamp,'Bonnie', 'Manes', 'Fully-configurable attitude-oriented portal');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (6, current_timestamp, current_timestamp,'Floyd', 'Terry', 'User-friendly encompassing data-warehouse');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (7, current_timestamp, current_timestamp,'Adriano', 'Mosconi', 'Mandatory systemic synergy');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (8, current_timestamp, current_timestamp,'Garreth', 'Canas', 'Ameliorated dedicated parallelism');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (9, current_timestamp, current_timestamp,'Janey', 'Lampet', 'Balanced attitude-oriented help-desk');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (10, current_timestamp,current_timestamp,'Hymie', 'Hallgath', 'Function-based object-oriented product');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (11, current_timestamp,current_timestamp,'Klara', 'Mulderrig', 'Multi-channelled directional paradigm');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (12, current_timestamp,current_timestamp,'Golda', 'O''Carrol', 'Cross-platform maximized internet solution');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (13, current_timestamp,current_timestamp,'Issiah', 'Daile', 'Cloned regional concept');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (14, current_timestamp,current_timestamp,'Seymour', 'Ridewood', 'Devolved optimizing moratorium');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (15, current_timestamp,current_timestamp,'Mellisa', 'Brecknell', 'Switchable neutral flexibility');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (16, current_timestamp,current_timestamp,'Adair', 'Pocknell', 'Pre-emptive multi-state process improvement');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (17, current_timestamp,current_timestamp,'Verina', 'Scamp', 'Cloned multimedia website');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (18, current_timestamp,current_timestamp,'Mada', 'Shermore', 'Optimized mobile groupware');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (19, current_timestamp,current_timestamp,'Myer', 'Durrad', 'Innovative user-facing neural-net');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (20, current_timestamp,current_timestamp,'Hervey', 'Delgardillo', 'Optional tangible customer loyalty');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (21, current_timestamp,current_timestamp,'Abrahan', 'Jaskowicz', 'Triple-buffered bandwidth-monitored parallelism');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (22, current_timestamp,current_timestamp,'Vikky', 'Jarvis', 'Ergonomic 3rd generation policy');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (23, current_timestamp,current_timestamp,'Augustine', 'Terrett', 'Configurable impactful throughput');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (24, current_timestamp,current_timestamp,'Gayla', 'Stenet', 'Automated contextually-based knowledge user');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (25, current_timestamp,current_timestamp,'Margot', 'Tretwell', 'Networked heuristic synergy');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (26, current_timestamp,current_timestamp,'Genna', 'Barmadier', 'Programmable discrete initiative');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (27, current_timestamp,current_timestamp,'Drona', 'De Maine', 'User-centric attitude-oriented access');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (28, current_timestamp,current_timestamp,'Lindy', 'Siegertsz', 'Open-source eco-centric benchmark');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (29, current_timestamp,current_timestamp,'Andreas', 'Catling', 'Synchronised bottom-line pricing structure');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (30, current_timestamp,current_timestamp,'Tobe', 'Cuberley', 'Enhanced actuating definition');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (31, current_timestamp,current_timestamp,'Jason', 'Selwyn', 'Re-contextualized optimal moderator');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (32, current_timestamp,current_timestamp,'Jannelle', 'Belson', 'Inverse value-added approach');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (33, current_timestamp,current_timestamp,'Derry', 'Bassill', 'Streamlined demand-driven archive');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (34, current_timestamp,current_timestamp,'Vergil', 'Guillerman', 'User-centric homogeneous portal');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (35, current_timestamp,current_timestamp,'Meggie', 'Carn', 'User-friendly hybrid attitude');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (36, current_timestamp,current_timestamp,'Gaven', 'Boord', 'Self-enabling client-server superstructure');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (37, current_timestamp,current_timestamp,'Hakim', 'Sketch', 'Ameliorated human-resource knowledge user');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (38, current_timestamp,current_timestamp,'Matty', 'Satch', 'Distributed intangible toolset');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (39, current_timestamp,current_timestamp,'Quintus', 'Sunderland', 'Decentralized client-server instruction set');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (40, current_timestamp,current_timestamp,'Dougie', 'Frantzen', 'Realigned multimedia infrastructure');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (41, current_timestamp,current_timestamp,'Theresa', 'Leverette', 'Robust object-oriented circuit');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (42, current_timestamp,current_timestamp,'Elga', 'Stampfer', 'Extended value-added Graphical User Interface');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (43, current_timestamp,current_timestamp,'Kelby', 'Leyson', 'Innovative logistical system engine');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (44, current_timestamp,current_timestamp,'Cortney', 'Voice', 'Synergized analyzing application');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (45, current_timestamp,current_timestamp,'Margareta', 'Tylor', 'Cross-group tangible function');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (46, current_timestamp,current_timestamp,'Desirae', 'Chattoe', 'Enterprise-wide eco-centric emulation');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (47, current_timestamp,current_timestamp,'Luis', 'Feldmesser', 'Monitored analyzing circuit');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (48, current_timestamp,current_timestamp,'Bart', 'Clyde', 'Profound mission-critical conglomeration');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (49, current_timestamp,current_timestamp,'Beilul', 'Joseland', 'Future-proofed zero defect moratorium');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (50, current_timestamp,current_timestamp,'Darnell', 'Pendrigh', 'Adaptive mobile matrices');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (51, current_timestamp,current_timestamp,'Andie', 'Halleybone', 'Advanced eco-centric solution');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (52, current_timestamp,current_timestamp,'Karole', 'Haggerstone', 'Up-sized needs-based project');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (53, current_timestamp,current_timestamp,'Magdaia', 'Cockshott', 'Robust well-modulated forecast');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (54, current_timestamp,current_timestamp,'Philomena', 'Fairhead', 'Mandatory heuristic product');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (55, current_timestamp,current_timestamp,'Zak', 'Tow', 'Universal directional info-mediaries');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (56, current_timestamp,current_timestamp,'Matthaeus', 'Kegley', 'Vision-oriented needs-based neural-net');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (57, current_timestamp,current_timestamp,'Maudie', 'Scotland', 'Mandatory actuating approach');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (58, current_timestamp,current_timestamp,'Nicolina', 'Andreichik', 'Implemented high-level matrices');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (59, current_timestamp,current_timestamp,'Herbie', 'Hurley', 'Distributed global analyzer');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (60, current_timestamp,current_timestamp,'Forster', 'Broomer', 'Proactive coherent archive');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (61, current_timestamp,current_timestamp,'Franny', 'O''Kynsillaghe', 'Optimized methodical installation');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (62, current_timestamp,current_timestamp,'Nance', 'Nutt', 'Switchable 24/7 secured line');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (63, current_timestamp,current_timestamp,'Drucie', 'Gladwell', 'Optimized homogeneous system engine');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (64, current_timestamp,current_timestamp,'Torey', 'Rouchy', 'User-friendly hybrid application');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (65, current_timestamp,current_timestamp,'Freddi', 'Langtree', 'Managed stable artificial intelligence');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (66, current_timestamp,current_timestamp,'Kariotta', 'Moorton', 'Polarised coherent capacity');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (67, current_timestamp,current_timestamp,'Mireille', 'Lezemere', 'Object-based object-oriented framework');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (68, current_timestamp,current_timestamp,'Arvie', 'Edyson', 'Distributed optimal algorithm');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (69, current_timestamp,current_timestamp,'Alejandra', 'Podbury', 'Phased multi-state internet solution');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (70, current_timestamp,current_timestamp,'Tremaine', 'Rathe', 'Configurable full-range product');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (71, current_timestamp,current_timestamp,'Hildagarde', 'Soro', 'Cross-platform directional open system');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (72, current_timestamp,current_timestamp,'Ramsay', 'Ell', 'Customer-focused human-resource project');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (73, current_timestamp,current_timestamp,'Nickolai', 'Craven', 'Inverse object-oriented flexibility');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (74, current_timestamp,current_timestamp,'Keri', 'Markovic', 'Open-source zero tolerance function');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (75, current_timestamp,current_timestamp,'Kathi', 'Hirjak', 'Object-based value-added collaboration');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (76, current_timestamp,current_timestamp,'Jaye', 'Kalberer', 'Multi-tiered contextually-based workforce');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (77, current_timestamp,current_timestamp,'Jervis', 'Gardiner', 'Compatible systematic adapter');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (78, current_timestamp,current_timestamp,'Clio', 'Grinaway', 'Versatile client-driven intranet');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (79, current_timestamp,current_timestamp,'Patrizia', 'Tuting', 'Object-based fault-tolerant collaboration');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (80, current_timestamp,current_timestamp,'Carla', 'Heady', 'Proactive cohesive standardization');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (81, current_timestamp,current_timestamp,'Carissa', 'Guiu', 'Devolved regional collaboration');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (82, current_timestamp,current_timestamp,'Leslie', 'Humpherson', 'Focused intangible strategy');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (83, current_timestamp,current_timestamp,'Tomasina', 'Higbin', 'Cross-group optimal capability');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (84, current_timestamp,current_timestamp,'Rosabelle', 'O''Flaverty', 'Triple-buffered dedicated architecture');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (85, current_timestamp,current_timestamp,'Chalmers', 'Turban', 'Stand-alone stable data-warehouse');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (86, current_timestamp,current_timestamp,'Marilee', 'Atchly', 'Multi-lateral high-level complexity');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (87, current_timestamp,current_timestamp,'Amalea', 'Eglaise', 'Front-line motivating monitoring');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (88, current_timestamp,current_timestamp,'Boycie', 'Sarl', 'Object-based stable forecast');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (89, current_timestamp,current_timestamp,'Farleigh', 'Lorryman', 'Polarised empowering help-desk');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (90, current_timestamp,current_timestamp,'Wally', 'Skym', 'Assimilated 4th generation superstructure');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (91, current_timestamp,current_timestamp,'Andee', 'Theuff', 'Re-engineered human-resource paradigm');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (92, current_timestamp,current_timestamp,'Fleur', 'Stearnes', 'Customizable regional moderator');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (93, current_timestamp,current_timestamp,'Kara-lynn', 'Beacon', 'Public-key heuristic support');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (94, current_timestamp,current_timestamp,'Erl', 'Gareisr', 'Advanced asymmetric application');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (95, current_timestamp,current_timestamp,'Ninnetta', 'O''Currine', 'Managed directional framework');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (96, current_timestamp,current_timestamp,'Fionna', 'Courage', 'Inverse system-worthy hierarchy');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (97, current_timestamp,current_timestamp,'Waldemar', 'Bellew', 'Object-based system-worthy utilisation');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (98, current_timestamp,current_timestamp,'Martainn', 'Caroline', 'Multi-layered analyzing infrastructure');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (99, current_timestamp,current_timestamp,'Genna', 'Wendover', 'Synchronised interactive firmware');
insert into author (id, create_date, edit_date, first_name, last_name, bio) values (100,current_timestamp,current_timestamp, 'Ira', 'Rishworth', 'Vision-oriented global orchestration');

insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (1, current_timestamp,current_timestamp, 'Marquita', '$421.33', '$434.49', 84);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (2, current_timestamp,current_timestamp, 'Harmonie', '$125.56', '$325.47', 4);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (3, current_timestamp,current_timestamp, 'Griffie', '$142.08', '$473.71', 16);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (4, current_timestamp,current_timestamp, 'Gregoire', '$352.99', '$37.43', 65);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (5, current_timestamp,current_timestamp, 'Shurlock', '$110.06', '$63.26', 38);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (6, current_timestamp,current_timestamp, 'Imogen', '$8.54', '$229.44', 80);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (7, current_timestamp,current_timestamp, 'Keven', '$106.78', '$147.40', 36);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (8, current_timestamp,current_timestamp, 'Lurleen', '$69.44', '$30.65', 84);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (9, current_timestamp,current_timestamp, 'Warren', '$395.99', '$144.51', 12);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (10, current_timestamp,current_timestamp, 'Shamus', '$302.63', '$176.00', 40);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (11, current_timestamp,current_timestamp, 'Lyn', '$189.76', '$16.14', 95);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (12, current_timestamp,current_timestamp, 'Libby', '$210.48', '$274.75', 41);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (13, current_timestamp,current_timestamp, 'Colas', '$6.50', '$434.19', 68);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (14, current_timestamp,current_timestamp, 'Cort', '$29.89', '$241.01', 16);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (15, current_timestamp,current_timestamp, 'Celestina', '$261.20', '$360.73', 22);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (16, current_timestamp,current_timestamp, 'Ian', '$362.69', '$414.50', 95);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (17, current_timestamp,current_timestamp, 'Kermie', '$128.39', '$189.49', 46);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (18, current_timestamp,current_timestamp, 'Stephanus', '$492.98', '$439.40', 89);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (19, current_timestamp,current_timestamp, 'Scott', '$295.39', '$373.40', 73);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (20, current_timestamp,current_timestamp, 'Puff', '$245.76', '$291.56', 41);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (21, current_timestamp,current_timestamp, 'Julius', '$167.81', '$363.62', 72);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (22, current_timestamp,current_timestamp, 'Janella', '$376.85', '$163.89', 29);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (23, current_timestamp,current_timestamp, 'Gale', '$231.25', '$17.12', 23);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (24, current_timestamp,current_timestamp, 'Filmer', '$451.69', '$441.45', 23);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (25, current_timestamp,current_timestamp, 'Mona', '$227.88', '$100.56', 43);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (26, current_timestamp,current_timestamp, 'Janka', '$2.61', '$305.94', 84);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (27, current_timestamp,current_timestamp, 'Nicola', '$166.48', '$299.75', 92);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (28, current_timestamp,current_timestamp, 'Madelle', '$384.36', '$104.11', 62);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (29, current_timestamp,current_timestamp, 'Anica', '$9.20', '$39.20', 46);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (30, current_timestamp,current_timestamp, 'Gasper', '$426.53', '$412.81', 35);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (31, current_timestamp,current_timestamp, 'Welbie', '$311.86', '$494.27', 15);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (32, current_timestamp,current_timestamp, 'Silvano', '$188.51', '$155.67', 1);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (33, current_timestamp,current_timestamp, 'Arty', '$134.17', '$69.87', 47);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (34, current_timestamp,current_timestamp, 'Mandie', '$253.72', '$372.33', 43);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (35, current_timestamp,current_timestamp, 'Halley', '$496.88', '$312.48', 93);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (36, current_timestamp,current_timestamp, 'Bartholemy', '$57.10', '$427.61', 3);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (37, current_timestamp,current_timestamp, 'Buddy', '$289.44', '$328.86', 41);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (38, current_timestamp,current_timestamp, 'Reuven', '$291.02', '$263.55', 50);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (39, current_timestamp,current_timestamp, 'Lizette', '$280.78', '$43.23', 6);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (40, current_timestamp,current_timestamp, 'Nonnah', '$223.08', '$173.94', 48);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (41, current_timestamp,current_timestamp, 'Irena', '$24.25', '$247.52', 81);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (42, current_timestamp,current_timestamp, 'Rupert', '$30.06', '$380.86', 94);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (43, current_timestamp,current_timestamp, 'Hashim', '$137.14', '$424.59', 62);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (44, current_timestamp,current_timestamp, 'Georgine', '$129.90', '$236.89', 69);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (45, current_timestamp,current_timestamp, 'Cross', '$159.46', '$359.32', 95);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (46, current_timestamp,current_timestamp, 'Tonnie', '$33.63', '$169.09', 15);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (47, current_timestamp,current_timestamp, 'Micky', '$497.24', '$124.61', 69);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (48, current_timestamp,current_timestamp, 'Camille', '$56.80', '$73.09', 8);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (49, current_timestamp,current_timestamp, 'Camila', '$92.70', '$243.09', 9);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (50, current_timestamp,current_timestamp, 'Marijo', '$488.35', '$241.86', 37);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (51, current_timestamp,current_timestamp, 'Dianemarie', '$91.40', '$495.78', 50);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (52, current_timestamp,current_timestamp, 'Rikki', '$75.45', '$472.03', 93);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (53, current_timestamp,current_timestamp, 'Merrill', '$372.39', '$90.65', 9);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (54, current_timestamp,current_timestamp, 'Leslie', '$353.58', '$456.87', 68);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (55, current_timestamp,current_timestamp, 'Rebeca', '$428.20', '$209.42', 69);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (56, current_timestamp,current_timestamp, 'Caprice', '$201.13', '$396.63', 84);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (57, current_timestamp,current_timestamp, 'Chrystel', '$45.72', '$319.47', 2);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (58, current_timestamp,current_timestamp, 'Luce', '$339.65', '$392.34', 66);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (59, current_timestamp,current_timestamp, 'Gabriele', '$477.35', '$221.94', 94);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (60, current_timestamp,current_timestamp, 'Toddie', '$422.65', '$151.67', 11);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (61, current_timestamp,current_timestamp, 'Selle', '$136.97', '$217.43', 96);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (62, current_timestamp,current_timestamp, 'Ryon', '$454.73', '$3.16', 44);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (63, current_timestamp,current_timestamp, 'Stewart', '$37.80', '$90.63', 82);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (64, current_timestamp,current_timestamp, 'Marmaduke', '$140.80', '$389.97', 90);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (65, current_timestamp,current_timestamp, 'Alecia', '$103.09', '$30.14', 28);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (66, current_timestamp,current_timestamp, 'Theadora', '$319.54', '$300.12', 78);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (67, current_timestamp,current_timestamp, 'Tulley', '$421.85', '$50.24', 50);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (68, current_timestamp,current_timestamp, 'Bianka', '$499.59', '$335.32', 54);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (69, current_timestamp,current_timestamp, 'Kerk', '$7.94', '$469.35', 10);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (70, current_timestamp,current_timestamp, 'Chev', '$303.99', '$264.18', 26);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (71, current_timestamp,current_timestamp, 'Robinet', '$67.96', '$314.07', 59);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (72, current_timestamp,current_timestamp, 'Ingrim', '$201.89', '$64.71', 100);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (73, current_timestamp,current_timestamp, 'Gray', '$236.31', '$31.17', 18);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (74, current_timestamp,current_timestamp, 'Tom', '$125.12', '$18.47', 45);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (75, current_timestamp,current_timestamp, 'Merilyn', '$250.73', '$138.06', 88);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (76, current_timestamp,current_timestamp, 'Sherill', '$229.65', '$483.97', 68);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (77, current_timestamp,current_timestamp, 'Pren', '$64.36', '$477.81', 11);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (78, current_timestamp,current_timestamp, 'Tricia', '$106.02', '$112.84', 29);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (79, current_timestamp,current_timestamp, 'Sawyere', '$250.76', '$363.93', 85);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (80, current_timestamp,current_timestamp, 'Terrill', '$159.73', '$56.67', 35);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (81, current_timestamp,current_timestamp, 'Kial', '$474.61', '$325.13', 21);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (82, current_timestamp,current_timestamp, 'Cristin', '$493.22', '$426.75', 85);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (83, current_timestamp,current_timestamp, 'Stormie', '$103.75', '$206.90', 89);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (84, current_timestamp,current_timestamp, 'Uriel', '$281.42', '$225.41', 90);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (85, current_timestamp,current_timestamp, 'Lois', '$288.24', '$136.50', 15);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (86, current_timestamp,current_timestamp, 'Jeniffer', '$301.69', '$274.45', 1);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (87, current_timestamp,current_timestamp, 'Emmy', '$135.85', '$344.37', 18);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (88, current_timestamp,current_timestamp, 'Eli', '$45.00', '$167.68', 68);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (89, current_timestamp,current_timestamp, 'Garald', '$119.62', '$191.37', 35);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (90, current_timestamp,current_timestamp, 'Zelda', '$290.93', '$349.71', 53);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (91, current_timestamp,current_timestamp, 'Garvey', '$255.66', '$356.90', 98);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (92, current_timestamp,current_timestamp, 'Arther', '$303.64', '$0.67', 92);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (93, current_timestamp,current_timestamp, 'Kienan', '$441.63', '$134.93', 92);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (94, current_timestamp,current_timestamp, 'Alvinia', '$471.23', '$166.61', 97);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (95, current_timestamp,current_timestamp, 'Seana', '$396.28', '$309.42', 14);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (96, current_timestamp,current_timestamp, 'Bennett', '$271.13', '$365.14', 70);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (97, current_timestamp,current_timestamp, 'Zed', '$275.22', '$291.98', 26);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (98, current_timestamp,current_timestamp, 'Phyllis', '$60.10', '$89.11', 91);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (99, current_timestamp,current_timestamp, 'Kaleena', '$33.75', '$342.90', 82);
insert into book (id, create_date, edit_date, title, price, price_old, author_id) values (100, current_timestamp,current_timestamp, 'Toddy', '$181.80', '$137.47', 60);